export const HOMEPAGE_FETCH_DATA_REQUEST = 'HOMEPAGE_FETCH_DATA_REQUEST'
export const HOMEPAGE_FETCH_DATA_SUCCESS = 'HOMEPAGE_FETCH_DATA_SUCCESS'
export const HOMEPAGE_FETCH_DATA_FAIL = 'HOMEPAGE_FETCH_DATA_FAIL'
//contact us
export const CONTACTUS_FETCH_DATA_REQUEST = 'CONTACTUS_FETCH_DATA_REQUEST'
export const CONTACTUS_FETCH_DATA_SUCCESS = 'CONTACTUS_FETCH_DATA_SUCCESS'
export const CONTACTUS_FETCH_DATA_FAIL = 'CONTACTUS_FETCH_DATA_FAIL'
//menu
export const MENU_FETCH_DATA_REQUEST = 'MENU_FETCH_DATA_REQUEST'
export const MENU_FETCH_DATA_SUCCESS = 'MENU_FETCH_DATA_SUCCESS'
export const MENU_FETCH_DATA_FAIL = 'MENU_FETCH_DATA_FAIL'
