//contactus
export const NEXT_SECTION_CONTACTUS = 'NEXT_SECTION_CONTACTUS'
export const PREV_SECTION_CONTACTUS = 'PREV_SECTION_CONTACTUS'
export const MOVE_TO_SECTION_CONTACTUS = 'MOVE_TO_SECTION_CONTACTUS'
//homepage
export const NEXT_SECTION_HOMEPAGE = 'NEXT_SECTION_HOMEPAGE'
export const PREV_SECTION_HOMEPAGE = 'PREV_SECTION_HOMEPAGE'
export const MOVE_TO_SECTION_HOMEPAGE = 'MOVE_TO_SECTION_HOMEPAGE'
//section1
export const NEXT_SLIDE_HOMEPAGE_SECTION1 = 'NEXT_SECTION_HOMEPAGE_SECTION1'
export const PREV_SLIDE_HOMEPAGE_SECTION1 = 'PREV_SLIDE_HOMEPAGE_SECTION1'
export const MOVE_TO_SLIDE_HOMEPAGE_SECTION1 = 'MOVE_TO_SLIDE_HOMEPAGE_SECTION1'
//about-us

export const NEXT_SECTION_ABOUTUS = 'NEXT_SECTION_ABOUTUS'
export const PREV_SECTION_ABOUTUS = 'PREV_SECTION_ABOUTUS'
export const MOVE_TO_SECTION_ABOUTUS = 'MOVE_TO_SECTION_ABOUTUS'

export const NEXT_SLIDE_ABOUTUS_SECTION2 = 'NEXT_SECTION_ABOUTUS_SECTION2'
export const PREV_SLIDE_ABOUTUS_SECTION2 = 'PREV_SLIDE_ABOUTUS_SECTION2'
export const MOVE_TO_SLIDE_ABOUTUS_SECTION2 = 'MOVE_TO_SLIDE_ABOUTUS_SECTION2'
export const MOVE_TO_SLIDE_ABOUTUS_SECTION5 = 'MOVE_TO_SLIDE_ABOUTUS_SECTION5'

export const MOVE_TO_SECTION_CAREER = 'MOVE_TO_SECTION_CAREER'
